// <auto-generated />
using System;
using DigiPro_ControlEscolar.Controllers;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DigiPro_ControlEscolar.Migrations
{
    [DbContext(typeof(MyDbContext))]
    [Migration("20201022000550_InitalCreate")]
    partial class InitalCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DigiPro_ControlEscolar.Controllers.Alumno", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ApMaterno")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ApPaterno")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DetAlumnosMateriasid")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.HasIndex("DetAlumnosMateriasid");

                    b.ToTable("Alumno");
                });

            modelBuilder.Entity("DigiPro_ControlEscolar.Controllers.DetAlumnosMaterias", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Alumnoid")
                        .HasColumnType("int");

                    b.Property<int>("Materiaid")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("Alumnoid");

                    b.HasIndex("Materiaid");

                    b.ToTable("DetAlumnosMaterias");
                });

            modelBuilder.Entity("DigiPro_ControlEscolar.Controllers.Materia", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ApPaterno")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Costo")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("DetAlumnosMateriasid")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("DetAlumnosMateriasid");

                    b.ToTable("Materia");
                });

            modelBuilder.Entity("DigiPro_ControlEscolar.Controllers.Alumno", b =>
                {
                    b.HasOne("DigiPro_ControlEscolar.Controllers.DetAlumnosMaterias", null)
                        .WithMany("Alumnos")
                        .HasForeignKey("DetAlumnosMateriasid");
                });

            modelBuilder.Entity("DigiPro_ControlEscolar.Controllers.DetAlumnosMaterias", b =>
                {
                    b.HasOne("DigiPro_ControlEscolar.Controllers.Alumno", "Alumno")
                        .WithMany()
                        .HasForeignKey("Alumnoid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DigiPro_ControlEscolar.Controllers.Materia", "Materia")
                        .WithMany()
                        .HasForeignKey("Materiaid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DigiPro_ControlEscolar.Controllers.Materia", b =>
                {
                    b.HasOne("DigiPro_ControlEscolar.Controllers.DetAlumnosMaterias", null)
                        .WithMany("Materias")
                        .HasForeignKey("DetAlumnosMateriasid");
                });
#pragma warning restore 612, 618
        }
    }
}
